version: "3.14"

services:
  postgres:
    container_name: lumbytes-typegraphql
    image: postgres:14.0
    environment:
      POSTGRES_USER: lumbytes
      POSTGRES_DB: lumbytes
      POSTGRES_PASSWORD: lumbytesDB2021
    volumes:
      - postgrestype:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

volumes:
  postgrestype: